
name: Flatpak Builder

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged

    steps:
      - uses: actions/checkout@v3

      - name: Flatpak build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          manifest-path: org.tlauncher.TLauncher.yml
          bundle: TLauncher.flatpak
